### PR TITLE
Added paragraph on channels being public, link to API key page and fixed typos

### PR DESCRIPTION
**Pull request by HenrikBengtsson**
Added paragraph on channels being public, link to API key page and fixed typos.

Remain known issues:
* The Pushbullet URLs to 'Getting Started' and 'Features' leads to nowhere.

### CODE REVIEW

**Comment by HenrikBengtsson** [comment]
**BUG FIX**: A dotfile with only one entry (e.g. 'key') would _not_ be read as a named character string (rather than a named list as code expect), e.g. 
```json
{
 "key": "aa...bb"
}
```

**ROBUSTNESS**: A dot file with a missing comma after 'key' would (silently) result in a `NULL` key, e.g.
```json
{
 "key": "aa...bb"    ## <= Missing comma!

 "devices": [
  "aa..bb"
 ],

 "names": [
  "Nexus 5"
 ]
}
```

PS. Sorry for the whitespace trimming; it's probably Emacs ESS doing it.

**Comment by eddelbuettel** [comment]
Well, the channels are public comments is nice, but semi-irrelevant. We are not here to explain all of Pushbullet (and its design strength and weaknesses to people). 

The Emacs trailing whitespace space issue is my bad. Seemingly I only clobber those in c, cpp, h, ... files.  Sorry that it inflates the patch.

The "only one key" fix is nice.

My projects all have `ChangeLog` in the top. Keepting those current while submitting multi-issue PRs is appreciated.

**Comment by eddelbuettel** [comment]
Also, it is always appreciated when existing indenting pattern are preserved. I use four, just like R sources.

**Comment by HenrikBengtsson** [comment]
Debated the "public channel" paragraph myself for that reason too (and it could become obsolete at any time), but the I figured I could spend others 30-60 mins searching for the answer.  The shorter version could have been "All channels are public.".

**Comment by eddelbuettel** [comment]
Yep, it is borderline.  If in doubt, better to have it.

Did you successfully all the (by default commented-out) test code in tests/?  I think we are getting ready for another release thanks to a lot of work by @mikebirdgeneau

**Pull request merged**
