### PR TITLE
Fix for issue #57: RPushbullet randomly failing to send pushes on Mac OS Catalina (10.15.1)

### PR DESCRIPTION
**Pull request by ashannon**
Changed `.getCurlHandle()` to make it use HTTP v1.1 instead of v2.0. This change has resolved my issue where `pbPost()` would randomly fail due to an an HTTP2 framing layer issue caused by `curl::curl_fetch_memory(pburl, handle=h)`

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Interesting.  @jeroen any comment?

Something went south with the PR though.  The diff is no diff but just a long `init.R`.  Not what you meant, is it?

**Comment by ashannon** [comment]
@eddelbuettel, this is my first attempt at making PR... It seems it didn't work the way I thought it would. 

Here's what I did: I forked your repo, downloaded the source, made a change to init.R (which contains the `.getCurlHandle()`), then made PR from this forked repo by uploading my modified version of init.R, whose only change is to add line 92. 

Just curious, what would be the preferred approach to submit a PR for this kind of small change?

**Comment by eddelbuettel** [comment]
The description of the process sounds right but maybe you got tripped up somewhere else.  See eg this from the most-recently-merged PR: some green (one line here), some red (also one).

**Comment by ashannon** [comment]
Sorry for that failed attempt at creating a PR. I think I got it right this time with #59.

**Comment by eddelbuettel** [comment]
Yes that one looks good.  Thanks for redoing it.

**Pull request closed without merging**
