### PR TITLE
Update .checkReturnCode to warn error content if it exists.

### PR DESCRIPTION
**Pull request by trshafer**
Add tests and testthat dependency.

This addresses the first concern in #63.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Truly sorry but that is why I prefer issue tickets with details over "blind" PRs. 

I prefer tinytest over testthat.  Here we have not needed either. Please convert to tests in the tests/ directory -- see `tests/simpleRests.R`.

**Comment by trshafer** [comment]
> Truly sorry but that is why I prefer issue tickets with details over "blind" PRs.

This PR is in direct response to the [comment in the attached issue](https://github.com/eddelbuettel/rpushbullet/issues/63#issuecomment-643425901): "Do you think you would have a chance to dive into the code and propose a change / fix?" Please advise.

Updated tests to use tinytest, but I am unsure how to run these tests, so just relying on travis testing to return success and error on pull request.

**Comment by eddelbuettel** [comment]
I appreciate that you are helping your dad out, but we are still talking past each other. There was not a single suggestion of "let's add a regression testing framework" when eight previous releases going back six full years did not need one.  RPushBullet still doesn't need one as all relevant tests really ... need a server backend responding much more that a collector of a few test results.  So I am not planning to add one. 

Now, back to the narrow issue of making a return error code more informative. I like want you did to `init.R`, the added line to `.gitignore` is fine too .... but is there a chance you could please express the tests with simpler `tryCatch()` or `try()` or ... logic?   Thanks for looking into that.

**Comment by trshafer** [comment]
I do not see value in reimplementing check_warning which uses tryCatch to validate warnings from tinytest: https://github.com/markvanderloo/tinytest/blob/4546bb26a156365efb5befe64b5118b423794167/pkg/R/expectations.R#L466. If this library is not interested in unit tests, I will not add them. I'm not here to argue on the merits of unit tests.

**Comment by eddelbuettel** [comment]
I appreciate the more minimal PR.

**Comment by eddelbuettel** [comment]
@trshafer : please see https://github.com/eddelbuettel/rpushbullet/commit/facd7dba695b564d2be7a607668535a72d82e38e for what I had in mind. Thanks for the tests ideas -- they were good.  I just, on balance, do not believe in a new dependency for three test expression (even though @markvanderloo is a pal and we were already laughing about the absurdity of this ticket).

All good now, and peace out!

**Comment by trshafer** [comment]
Sounds good. Thanks for adding the tests!

**Pull request merged**
