### PR TITLE
add pbGetPost function and modify .createPush for this

### PR DESCRIPTION
**Pull request by mrchypark**
add function to get post using pushbullet api https://docs.pushbullet.com/#list-pushes.

only add param limit first.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Can you think of a possible test?  For now a few lines in [simpleTests.R](https://github.com/eddelbuettel/rpushbullet/blob/master/tests/simpleTests.R) would do.

**Comment by mrchypark** [comment]
Can you explain about simpleTests.R now? If it can check post count, will be great.

I set test post count == 0 first, and test again end of test and check post count > 0.
Is it right beginning of test, post count is 0?

**Comment by eddelbuettel** [comment]
Yes count changing from zero to greater than zero after we do one of the pushes should do.

**Comment by eddelbuettel** [comment]
Made a minimal change to "plural" in the function name as multiple posts may get returned.

**Pull request merged**
