### PR TITLE
Feature/travis with token

### PR DESCRIPTION
**Pull request by eddelbuettel**
=:-) 

We now have Travis tests

### CODE REVIEW

**Comment by restonslacker** [comment]
Very nice!

**Comment by eddelbuettel** [comment]
Hope we didn't jinx it. Promptly failed.  May have been temporary. Running now.

And I gamed the coverage stats like the best of them :)

Shall we turn off the @nord tags you added?  _If_ documentation was written why not show it?

**Comment by restonslacker** [comment]
Ha!

WRT the @nord tag, those were only on the .isValid* functions which aren't currently exported. I wanted to leave documentation for other devs including Future Seth but didn't want to expose it in the help file. If you want to make those methods public then by all means remove the tags.

**Comment by eddelbuettel** [comment]
Weird.  

I created the encoded file in an ad-hoc Docker container (so as to not spill all those Ruby gems needed to run the `travis` command-line tool).  And I then created a new encoded file (with a throw-away GMail account for accessing a Google API) which is not yet deployed.  Seems as if that had a side effect with this token.

Very strange.  Well, repaired now.  We'll see how fragile it is.  If it is too much of a mess we can always turn the two env vars in `.travis.yml` back off again.

**Pull request merged**
